//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oksman_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public int BookingID { get; set; }
        public int Complete { get; set; }
        public Nullable<System.DateTime> BookedDate { get; set; }

        public decimal TotalPrice { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
